const products = [{
        _id: '1',
        name: 'X1 Pencil',
        image: '/images/X1.jpeg',
        description: "It is the very cool pencil. I am just testing it in computer but I already like it. It is my favourite kind of pecil. And I don't know what I am writing but it is just to test if I can fit this content in the web. Thank you",
        brand: 'DOMS',
        category: 'Pencil',
        price: 80.00,
        countInStock: 50,
        rating: 4.5,
        numReviews: 5,
    },
    {
        _id: '2',
        name: 'Y1 Pencil',
        image: '/images/Y1.jpeg',
        description: '',
        brand: 'DOMS',
        category: 'Pencil',
        price: 70.00,
        countInStock: 50,
        rating: 4.0,
        numReviews: 5,
    },
    {
        _id: '3',
        name: 'Zoom Trangular Pencil',
        image: '/images/zoom_tri.jpeg',
        description: '',
        brand: 'DOMS',
        category: 'Pencil',
        price: 70.00,
        countInStock: 50,
        rating: 4.0,
        numReviews: 5,
    },
    {
        _id: '4',
        name: 'Non Dust Eraser',
        image: '/images/non_dust.jpeg',
        description: '',
        brand: 'DOMS',
        category: 'Pencil',
        price: 70.00,
        countInStock: 50,
        rating: 4.0,
        numReviews: 5,
    },
    {
        _id: '5',
        name: 'Regular Sharpner',
        image: '/images/regular_sharpner.jpeg',
        description: '',
        brand: 'DOMS',
        category: 'Pencil',
        price: 70.00,
        countInStock: 50,
        rating: 4.0,
        numReviews: 5,
    },
    {
        _id: '6',
        name: 'Water Color (mini)',
        image: '/images/water_color.jpeg',
        description: '',
        brand: 'DOMS',
        category: 'Pencil',
        price: 70.00,
        countInStock: 50,
        rating: 4.0,
        numReviews: 5,
    },
    {
        _id: '7',
        name: 'Pencil Color',
        image: '/images/pencil_color.jpeg',
        description: '',
        brand: 'DOMS',
        category: 'Pencil',
        price: 70.00,
        countInStock: 50,
        rating: 0.7,
        numReviews: 5,
    }

]

export default products